# Exercises {#sec-exercises}

```{r setup, echo=FALSE, results="asis"}
library(rebook)
chapterPreamble()
```

You can find assignments from the end of each chapters. For example solutions,
see [@exercises-solutions].

::: {.callout-tip}
## Tips for exercises

- Add clear comments explaining each line or section of code. This enhances
understanding for both you and others, aids in debugging, facilitates code
reuse, and promotes transparency.
- Interpret results by comparing them to existing literature. Summarize key
findings to ensure they are easily understandable, even for those without
advanced expertise in data analytics.
- Avoid hard-coding values. Instead, define variables at the start of the
code chunk to make parameter adjustments easier and improve code reusability.

:::

## Basics of R/Bioconductor

Bioconductor training material has been contributed to
[Carpentries](https://carpentries.org/). You can check the following lessons
for basic background of R and Bioconductor.

 * [Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/)

 * [Introduction to the Bioconductor project](https://carpentries-incubator.github.io/bioc-project/)
